import type { Metadata } from "next";
import {  ConfigProvider } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
         <ConfigProvider
   theme={{
    components: {
      Button: {
        defaultActiveBorderColor:"rgb(50,105,245)",
        defaultActiveColor:"rgb(50,105,245)"
      },
      Input: {
        colorPrimary: '#eb2f96',
        algorithm: true, // Enable algorithm
      }
    },
  }}
  >
       <AntdRegistry>{children}</AntdRegistry>
       </ConfigProvider>
      </body>
    </html>
  );
}
